<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\boom.mp3" />
    <None Remove="Assets\Người Im Lặng Gặp Người Hay Nói - HIEUTHUHAI.mp3" />
    <None Remove="Assets\SpotiDownloader.com - IDNAT %28IM ĐỢI NGƯỜI ANH THƯƠNG%29 - TINH HÀ _SAY HI_ %281%29.mp3" />
    <None Remove="Assets\SpotiDownloader.com - Yes or No - Jung Kook.mp3" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\boom.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Người Im Lặng Gặp Người Hay Nói - HIEUTHUHAI.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\SpotiDownloader.com - IDNAT (IM ĐỢI NGƯỜI ANH THƯƠNG) - TINH HÀ _SAY HI_ (1).mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\SpotiDownloader.com - Yes or No - Jung Kook.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
